// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

////////
// Wi-Fi Control Functions
// These functions manage the Wi-Fi connection and its status

// Open/Enable Wi-Fi connection
void WIFIOPEN(lv_event_t * e);

// Close/Disable Wi-Fi connection
void WIFICLOSE(lv_event_t * e);

// Handle Wi-Fi connection (e.g., connect to a network with provided credentials)
void WIFIConnection(lv_event_t * e);


// Password Display Functions
// These functions manage the display of Wi-Fi passwords

// Access Point Wi-Fi Control Functions
// These functions are used to manage the device's Wi-Fi Access Point (AP) mode

// Open or start the Wi-Fi Access Point mode (turn the device into a hotspot)
void WIFIAPOPEN(lv_event_t * e);

// Close or stop the Wi-Fi Access Point mode (disable the hotspot)
void WIFIAPCLOSE(lv_event_t * e);
////////

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
