// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel6;
extern void ui_event_Image8(lv_event_t * e);
extern lv_obj_t * ui_Image8;
extern void ui_event_Image9(lv_event_t * e);
extern lv_obj_t * ui_Image9;
extern void ui_event_Image10(lv_event_t * e);
extern lv_obj_t * ui_Image10;
extern void ui_event_Image11(lv_event_t * e);
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label7;
extern void ui_event_Image13(lv_event_t * e);
extern lv_obj_t * ui_Image13;
extern void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern void ui_event_Image15(lv_event_t * e);
extern lv_obj_t * ui_Image15;
extern void ui_event_Image16(lv_event_t * e);
extern lv_obj_t * ui_Image16;
extern void ui_event_Image17(lv_event_t * e);
extern lv_obj_t * ui_Image17;
extern void ui_event_Image21(lv_event_t * e);
extern lv_obj_t * ui_Image21;
extern void ui_event_Image26(lv_event_t * e);
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image18;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

