// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN7_H
#define UI_SCREEN7_H

#ifdef __cplusplus
extern "C" {
#endif



// SCREEN: ui_Screen7
extern void ui_Screen7_screen_init(void);
extern void ui_Screen7_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Keyboard2;
extern void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image26;


extern lv_obj_t * ui_Image27 ;
extern lv_obj_t * ui_Image28 ;
extern lv_obj_t * ui_Image29 ;
extern lv_obj_t * ui_Image30 ;
extern lv_obj_t * ui_Image31 ;



// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
