// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
extern void ui_event_Image2(lv_event_t * e);
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern void ui_event_Image3(lv_event_t * e);
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label4;
extern void ui_event_Image4(lv_event_t * e);
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label5;
extern void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image6;

/////////
extern lv_obj_t *ui_Screen1_WifiIcon;
extern lv_obj_t *ui_Screen1_WifiLabel;
///////
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

