// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "stdio.h"// để sử dụng hàm printf
#include "esp_mqtt_client/esp_mqtt_client.h"

#define USERNAME_MAX_LEN   64
#define PASSWORD_MAX_LEN   64

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Image24 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_Image25 = NULL;
lv_obj_t * ui_Image26 = NULL;
lv_obj_t * ui_Label15 = NULL;


lv_obj_t * ui_Image27 = NULL;
lv_obj_t * ui_Image28 = NULL;
lv_obj_t * ui_Image29 = NULL;
lv_obj_t * ui_Image30 = NULL;
lv_obj_t * ui_Image31 = NULL;

static lv_obj_t * area = NULL;



char g_username[USERNAME_MAX_LEN];
char g_password[PASSWORD_MAX_LEN];

lv_obj_t * ui_EyeIcon;
static bool password_visible = false;

extern char device_mac[18];

extern esp_mqtt_client_handle_t mqttClient;

static int click_count = 0;
static uint32_t last_click_time = 0;
static int change=0;
static int cnt=0;
uint8_t max_touch_cnt=3; 



// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Image25, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Label14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);


    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        /*
        const char * txt = lv_textarea_get_text(ui_TextArea1);
        strncpy(g_username, txt, USERNAME_MAX_LEN - 1);
        g_username[USERNAME_MAX_LEN - 1] = '\0';
        printf("USERNAME = %s\n", g_username);
        */


        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Image25, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Image25, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
         _ui_flag_modify(ui_Label14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

    }
}

void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_Image25, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Label14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

    }
    if(event_code == LV_EVENT_READY) {
        /*
        const char * txt = lv_textarea_get_text(ui_TextArea2);
        strncpy(g_password, txt, PASSWORD_MAX_LEN - 1);
        g_password[PASSWORD_MAX_LEN - 1] = '\0';
        printf("PASSOWRD = %s\n", g_password);
        */
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Image25, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Image25(lv_event_t * e)
{   
    //char mess[128];
    char mess[200];
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Label14, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);

        const char * txt1 = lv_textarea_get_text(ui_TextArea1);
        strncpy(g_username, txt1, USERNAME_MAX_LEN - 1);
        g_username[USERNAME_MAX_LEN - 1] = '\0';
        printf("USERNAME = %s\n", g_username);

        const char * txt2 = lv_textarea_get_text(ui_TextArea2);
        strncpy(g_password, txt2, USERNAME_MAX_LEN - 1);
        g_password[USERNAME_MAX_LEN - 1] = '\0';
        printf("PASSWORD = %s\n", g_password);

        if (txt1!=NULL&&txt2!=NULL){

        snprintf(mess,sizeof(mess),"{\"device_id\":\"%s\",\"username\":\"%s\",\"password\":\"%s\"}",device_mac,g_username,g_password); 
    	int msg_id = esp_mqtt_client_publish(mqttClient, "devicelogin", mess, 0, 0, 0);

        if (msg_id == -1){
           ESP_LOGE("MQTT", "Failed to send login data");
           
         }
        else{
           ESP_LOGI("MQTT", "login data sent successfully, msg_id=%d", msg_id);

        }
        lv_textarea_set_text(ui_TextArea1,"");
        lv_textarea_set_text(ui_TextArea2,"");


    }

    }

}

static void area_click_event_cb(lv_event_t *e) {
        uint32_t current_time = lv_tick_get();

    if ((current_time - last_click_time) < 5000) {
        click_count++;
    } else {
        click_count = 1;
        last_click_time = current_time;
    }

    if (click_count >= max_touch_cnt) {
        click_count = 0;
        change=1;//
        _ui_flag_modify(ui_WIFI_PWD_Error, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);//
        _ui_screen_change(&ui_Main_WIFI, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Wifi_Screen_init);
       // _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Screen4_screen_init);


        /////////
        if (cnt!=0){

    // Bắt đầu scan Wi-Fi (non-blocking)
    //wifi_scan();
    _ui_state_modify(ui_WIFI_OPEN, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);//
    lv_obj_clean(ui_WIFI_SCAN_List);
    _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    _ui_flag_modify(ui_WIFI_Spinner, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE); //
     
    WIFI_SCAN_FLAG=true;
}

    }
    
    last_click_time = current_time;
}

void ui_event_eye_icon(lv_event_t * e)
{
    if(lv_event_get_code(e) == LV_EVENT_CLICKED) {

        password_visible = !password_visible;

        lv_textarea_set_password_mode(ui_TextArea2, !password_visible);

        lv_label_set_text(
            ui_EyeIcon,
            password_visible ? LV_SYMBOL_EYE_OPEN : LV_SYMBOL_EYE_CLOSE
        );

        lv_obj_invalidate(ui_TextArea2);
    }
}





// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label13, -356);
    //lv_obj_set_y(ui_Label13, -78);
    //lv_obj_set_x(ui_Label13, -302);
    //lv_obj_set_x(ui_Label13, -332);
    lv_obj_set_x(ui_Label13, -252);

    lv_obj_set_y(ui_Label13, -104);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "USERNAME");
    //lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_BOLD_VN30, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Label14 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label14, -302);
    //lv_obj_set_x(ui_Label14, -332);
    lv_obj_set_x(ui_Label14, -252);


    lv_obj_set_y(ui_Label14, -8);
    //lv_obj_set_x(ui_Label14, -351);
    //lv_obj_set_y(ui_Label14, 30);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "PASSWORD");
    //lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_BOLD_VN30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen7);
    /*
    lv_obj_set_width(ui_Keyboard1, 931);
    lv_obj_set_height(ui_Keyboard1, 177);
    lv_obj_set_x(ui_Keyboard1, 7);
    lv_obj_set_y(ui_Keyboard1, 186);
*/
    lv_obj_set_width(ui_Keyboard1, 931);
    lv_obj_set_height(ui_Keyboard1, 249);
    lv_obj_set_x(ui_Keyboard1, 7);
    lv_obj_set_y(ui_Keyboard1, 169);

    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_Panel12 = lv_obj_create(ui_Screen7);
    lv_obj_set_width(ui_Panel12, 1028);
    lv_obj_set_height(ui_Panel12, 130);
    lv_obj_set_x(ui_Panel12, 0);
    lv_obj_set_y(ui_Panel12, -237);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xA59898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image24, &ui_img_27268529);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image24, -5);
    lv_obj_set_y(ui_Image24, 0);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    area=lv_obj_create(ui_Panel12);
    lv_obj_set_width(area, 120);   
    lv_obj_set_height(area, 120);    
    lv_obj_set_style_bg_color(area,lv_color_hex(0xA59898),LV_PART_MAIN|LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(area, lv_color_hex(0xA59898), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_x(area, -20);
    lv_obj_set_y(area, -20);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen7);
    /*
    lv_obj_set_width(ui_Keyboard2, 931);
    lv_obj_set_height(ui_Keyboard2, 177);
    lv_obj_set_x(ui_Keyboard2, 7);
    lv_obj_set_y(ui_Keyboard2, 186);
*/
    lv_obj_set_width(ui_Keyboard2, 931);
    lv_obj_set_height(ui_Keyboard2, 249);
    lv_obj_set_x(ui_Keyboard2, 7);
    lv_obj_set_y(ui_Keyboard2, 169);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen7);
    /*
    lv_obj_set_width(ui_TextArea1, 611);
    lv_obj_set_height(ui_TextArea1, 80);
    lv_obj_set_x(ui_TextArea1, 115);
    lv_obj_set_y(ui_TextArea1, -78);
*/
    //lv_obj_set_width(ui_TextArea1, 611);
    lv_obj_set_width(ui_TextArea1, 410);

    lv_obj_set_height(ui_TextArea1, 80);
    //lv_obj_set_x(ui_TextArea1, 115);
    //lv_obj_set_x(ui_TextArea1, 85);
    lv_obj_set_x(ui_TextArea1, 65);

    lv_obj_set_y(ui_TextArea1, -103);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    //lv_textarea_set_max_length(ui_TextArea1, 18);//
    lv_textarea_set_max_length(ui_TextArea1, 64);//


/*
    ui_TextArea2 = lv_textarea_create(ui_Screen7);

    lv_obj_set_width(ui_TextArea2, 611);
    lv_obj_set_height(ui_TextArea2, 80);
    lv_obj_set_x(ui_TextArea2, 85);
    lv_obj_set_y(ui_TextArea2, -8);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    ui_EyeIcon = lv_label_create(ui_TextArea2);
    lv_label_set_text(ui_EyeIcon, LV_SYMBOL_EYE_CLOSE);

    lv_obj_set_style_text_font(ui_EyeIcon, &lv_font_montserrat_30,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextArea2, 40,
                           LV_PART_MAIN | LV_STATE_DEFAULT);


    lv_obj_align(ui_EyeIcon, LV_ALIGN_RIGHT_MID, -10, 0);

    lv_obj_add_flag(ui_EyeIcon, LV_OBJ_FLAG_CLICKABLE);

    lv_textarea_set_password_mode(ui_TextArea2, true);// áº©n password
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_TextArea2, 18);//
*/
lv_obj_t *cont = lv_obj_create(ui_Screen7);
//lv_obj_set_size(cont, 611, 80);
lv_obj_set_size(cont, 410, 80);
//lv_obj_align(cont, LV_ALIGN_CENTER, 85, -8);
lv_obj_align(cont, LV_ALIGN_CENTER, 65, -8);

lv_obj_clear_flag(cont, LV_OBJ_FLAG_SCROLLABLE);

ui_TextArea2 = lv_textarea_create(cont);
//lv_obj_set_size(ui_TextArea2, 611, 80);
lv_obj_set_size(ui_TextArea2, 410, 80);

lv_obj_align(ui_TextArea2, LV_ALIGN_CENTER, 0, 0);
lv_obj_set_style_pad_right(ui_TextArea2, 50, 0);

ui_EyeIcon = lv_label_create(cont);
lv_label_set_text(ui_EyeIcon, LV_SYMBOL_EYE_CLOSE);
lv_obj_align(ui_EyeIcon, LV_ALIGN_RIGHT_MID, -10, 0);
lv_obj_set_style_text_font(ui_EyeIcon, &lv_font_montserrat_30, LV_PART_MAIN);//
lv_obj_set_style_pad_right(ui_TextArea2, 65, LV_PART_MAIN);//



lv_obj_add_flag(ui_EyeIcon, LV_OBJ_FLAG_CLICKABLE);

lv_textarea_set_password_mode(ui_TextArea2, true);// áº©n password
lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
//lv_textarea_set_max_length(ui_TextArea2, 18);//
lv_textarea_set_max_length(ui_TextArea2, 64);//







    ui_Image25 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image25, &ui_img_637022296);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image25, 445);
    lv_obj_set_y(ui_Image25, 246);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_CLICKABLE);//

    ui_Image26 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image26, &ui_img_705274890);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image26, -480);
    lv_obj_set_y(ui_Image26, 262);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Screen7);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 9);
    lv_obj_set_y(ui_Label14, 159);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "USERNAME HOẶC PASSWORD KHÔNG ĐÚNG!");
    lv_obj_add_flag(ui_Label14, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xE31A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_BOLD_VN30, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Image27 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image27, &ui_img_nowifi3_50x50_trans_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image27, 461);
    lv_obj_set_y(ui_Image27, -263);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image28 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image28, &ui_img_wifi1_tran_png);
    lv_obj_set_width(ui_Image28, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image28, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image28, 461);
    lv_obj_set_y(ui_Image28, -263);
    lv_obj_set_align(ui_Image28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image28, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image29 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image29, &ui_img_785059581);
    lv_obj_set_width(ui_Image29, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image29, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image29, 461);
    lv_obj_set_y(ui_Image29, -263);
    lv_obj_set_align(ui_Image29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image29, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image30 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image30, &ui_img_1279478591);
    lv_obj_set_width(ui_Image30, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image30, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image30, 461);
    lv_obj_set_y(ui_Image30, -263);
    lv_obj_set_align(ui_Image30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image30, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image31 = lv_img_create(ui_Screen7);
    lv_img_set_src(ui_Image31, &ui_img_776640815);
    lv_obj_set_width(ui_Image31, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image31, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image31, 461);
    lv_obj_set_y(ui_Image31, -263);
    lv_obj_set_align(ui_Image31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image31, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags



    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
    lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen7, ui_event_Screen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_EyeIcon, ui_event_eye_icon, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_Image25, ui_event_Image25, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(area, area_click_event_cb, LV_EVENT_CLICKED, NULL);


}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Keyboard1 = NULL;
    ui_Panel12 = NULL;
    ui_Image24 = NULL;
    ui_Keyboard2 = NULL;
    ui_TextArea1 = NULL;
    ui_TextArea2 = NULL;
    ui_Image25 = NULL;

}