// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "esp_mqtt_client.h"
#include "lvgl_port.h"

lv_obj_t * ui_Screen11 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
lv_obj_t * ui_TextArea2 = NULL;
lv_obj_t * ui_TextArea3 = NULL;
lv_obj_t * ui_TextArea4 = NULL;

lv_obj_t * Enter_Button = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label32 = NULL;

lv_obj_t * ui_Keyboard3 = NULL;
lv_obj_t * ui_Keyboard4 = NULL;


lv_obj_t * ui_Image45 = NULL;



char input_buffer[17]={0};
// event funtions
/*
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {

        
        lv_obj_add_flag(ui_Keyboard2,LV_OBJ_FLAG_HIDDEN);


    }
   
}


void ui_event_TextArea3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
      

        lv_obj_add_flag(ui_Keyboard3,LV_OBJ_FLAG_HIDDEN);



    }
   
}
*/



void ui_event_TextArea4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_Keyboard4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Keyboard4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
      

        lv_obj_add_flag(ui_Keyboard4,LV_OBJ_FLAG_HIDDEN);
        lv_textarea_set_cursor_click_pos(ui_TextArea4,false);


    }
   
}




void ui_event_Back_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen9, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen9_screen_init);
    }
}


void ui_event_Enter_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {

         //const char *txt3 = lv_textarea_get_text(ui_TextArea3);
        // const char *txt2 = lv_textarea_get_text(ui_TextArea2);
         const char *txt4 = lv_textarea_get_text(ui_TextArea4);


/*
         if (txt2[0]!='0'&&strlen(txt2)>0){
         strncpy(input_buffer, txt2, sizeof(input_buffer));
         input_buffer[sizeof(input_buffer)-1] = '\0';  
         save_current_number(input_buffer);
         }
         else if (txt2[0]=='0'&&strlen(txt2)>0) {
            delete_current_number();
            */
            /*
            if (lvgl_port_lock(-1)){
            lv_textarea_set_placeholder_text(ui_TextArea2, "0000");
            lvgl_port_unlock();
            }
            */
      //   }

/*
         if (txt3[0]!='0'&&strlen(txt3)>0){

         strncpy(input_buffer, txt3, sizeof(input_buffer));
         input_buffer[sizeof(input_buffer)-1] = '\0';  
         save_next_number(input_buffer);
         }
         else if  (txt3[0]=='0'&&strlen(txt3)>0)  {
            delete_next_number();
         }
*/
         if (txt4[0]!='0'&&strlen(txt4)>0){

         strncpy(input_buffer, txt4, sizeof(input_buffer));
         input_buffer[sizeof(input_buffer)-1] = '\0';  

         uint8_t x=0;

         for (int i=0;input_buffer[i]!='\0';i++){
            x=x*10+input_buffer[i]-'0';
         }

         ESP_LOGI("SAVE TIMEOUT","%d",x);
         
         save_timeout(x);
         }
         
         
         else if  (txt4[0]=='0'&&strlen(txt4)>0)  {
            delete_next_number();
         }
         
         
        // lv_textarea_set_text(ui_TextArea2,"");
         //lv_textarea_set_text(ui_TextArea3,"");
         lv_textarea_set_text(ui_TextArea4,"");

        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen11_screen_init(void)
{
    ui_Screen11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    /*
    ui_Keyboard2 = lv_keyboard_create(ui_Screen11);
    lv_obj_set_width(ui_Keyboard2, 929);
    lv_obj_set_height(ui_Keyboard2, 177);
    //lv_obj_set_x(ui_Keyboard2, -24);
    //lv_obj_set_y(ui_Keyboard2, 105);
    lv_obj_set_x(ui_Keyboard2, -2);
    lv_obj_set_y(ui_Keyboard2, 110);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2,LV_OBJ_FLAG_HIDDEN);

    ui_TextArea2 = lv_textarea_create(ui_Screen11);
    */
    /*
    lv_obj_set_width(ui_TextArea2, 461);
    lv_obj_set_height(ui_TextArea2, 70);
    lv_obj_set_x(ui_TextArea2, -38);
    lv_obj_set_y(ui_TextArea2, -165);
    */
   /*
    lv_obj_set_width(ui_TextArea2, 187);
    lv_obj_set_height(ui_TextArea2, 60);
    lv_obj_set_x(ui_TextArea2, 1);
    lv_obj_set_y(ui_TextArea2, -139);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    //lv_textarea_set_placeholder_text(ui_TextArea2, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_TextArea2, 4);

*/
    
    Enter_Button = lv_btn_create(ui_Screen11);

    lv_obj_set_width(Enter_Button, 137);                                                              // Set button width
    lv_obj_set_height(Enter_Button, 50);                                                              // Set button height
    lv_obj_add_flag(Enter_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scrolling on focus
    lv_obj_clear_flag(Enter_Button, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling
    lv_obj_set_style_bg_color(Enter_Button, lv_color_hex(0x0080FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_align(Enter_Button, LV_ALIGN_TOP_LEFT, 20, 20);
    


    

    ui_WIFI_Label0 = lv_label_create(Enter_Button);
    lv_obj_set_width(ui_WIFI_Label0, LV_SIZE_CONTENT);                                                    // Set label width based on content
    lv_obj_set_height(ui_WIFI_Label0, LV_SIZE_CONTENT);                                                   // Set label height based on content
    lv_obj_set_align(ui_WIFI_Label0, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_WIFI_Label0, "ENTER");                                                      // Set button label text
    lv_obj_set_style_text_color(ui_WIFI_Label0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); 
    lv_obj_set_style_text_opa(ui_WIFI_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_WIFI_Label0, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);


   // lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);

    

    /*
    ui_TextArea3 = lv_textarea_create(ui_Screen11);
   // lv_obj_set_width(ui_TextArea3, 461);
   // lv_obj_set_height(ui_TextArea3, 70);
   // lv_obj_set_x(ui_TextArea3, -38);
    lv_obj_set_width(ui_TextArea3, 187);
    lv_obj_set_height(ui_TextArea3, 60);
    lv_obj_set_x(ui_TextArea3, 1);
    lv_obj_set_y(ui_TextArea3, -75);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    //lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");
    lv_obj_set_style_text_font(ui_TextArea3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_TextArea3, 4);
*/

    
    ui_Image45 = lv_img_create(ui_Screen11);
    lv_img_set_src(ui_Image45, &ui_img_turn_back2_png);
    lv_obj_set_width(ui_Image45, LV_SIZE_CONTENT);   /// 70
    lv_obj_set_height(ui_Image45, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Image45, -447);
    lv_obj_set_y(ui_Image45, 247);
    lv_obj_set_align(ui_Image45, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image45, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_add_flag(ui_Image45,LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_Image45, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    /*
    ui_Label30 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label30, -397);
    //lv_obj_set_y(ui_Label30, -171);
    lv_obj_set_x(ui_Label30, -210);
    lv_obj_set_y(ui_Label30, -143);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "SỐ HIỆN TẠI");
    */

    /*
    char tmp_cur[5];
    if (read_number(tmp_cur,sizeof(tmp_cur))==ESP_OK){ 
        if (lvgl_port_lock(-1)){
        lv_textarea_set_placeholder_text(ui_TextArea2, tmp_cur);
        lvgl_port_unlock();
        }
    }

      else {
    if (lvgl_port_lock(-1)){
    lv_textarea_set_placeholder_text(ui_TextArea2, "0000");
    lvgl_port_unlock();
    }

   }
    */

    /*

    lv_obj_set_style_text_font(ui_Label30, &ui_font_BOLD_VN25, LV_PART_MAIN | LV_STATE_DEFAULT);
    

    ui_Label31 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label31, -386);
    lv_obj_set_x(ui_Label31, -196);
    lv_obj_set_y(ui_Label31, -77);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "SỐ TIẾP THEO");
    */

    /*
    char tmp_next[5];
    if (read_next_number(tmp_next,sizeof(tmp_next))==ESP_OK){
    if (lvgl_port_lock(-1)){
    lv_textarea_set_placeholder_text(ui_TextArea3, tmp_next);
    lvgl_port_unlock();
    }
   }
   else {
    if (lvgl_port_lock(-1)){
    lv_textarea_set_placeholder_text(ui_TextArea3, "0000");
    lvgl_port_unlock();
    }

   }
    */
    
    //lv_obj_set_style_text_font(ui_Label31, &ui_font_BOLD_VN25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_Screen11);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_x(ui_Label32, -386);
    //lv_obj_set_x(ui_Label32, -217);
    //lv_obj_set_y(ui_Label32, -14);
    lv_obj_set_x(ui_Label32, -255);
    lv_obj_set_y(ui_Label32, -167);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "THỜI GIAN CHỜ (S)");
    lv_obj_set_style_text_font(ui_Label32, &ui_font_BOLD_VN25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea4 = lv_textarea_create(ui_Screen11);

    lv_obj_set_width(ui_TextArea4, 187);
    lv_obj_set_height(ui_TextArea4, 60);
    //lv_obj_set_x(ui_TextArea4, 1);
    //lv_obj_set_y(ui_TextArea4, -11);
    lv_obj_set_x(ui_TextArea4, -38);
    lv_obj_set_y(ui_TextArea4, -165);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);

    uint8_t tmp;
    char str[10];
    if ( read_time(&tmp)==ESP_OK&&tmp>0){
        
        sprintf(str,"%d",tmp);
    }
    else {
        sprintf(str,"10");
    }
    
    //lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");
    lv_textarea_set_placeholder_text(ui_TextArea4, str);

    lv_obj_set_style_text_font(ui_TextArea4, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_TextArea4, 4);

    ui_Keyboard3 = lv_keyboard_create(ui_Screen11);
   // lv_obj_set_width(ui_Keyboard3, 929);
   // lv_obj_set_height(ui_Keyboard3, 177);
    //lv_obj_set_width(ui_TextArea2, 187);
    //lv_obj_set_height(ui_TextArea2, 60);
    //lv_obj_set_x(ui_Keyboard3, -24);
    //lv_obj_set_y(ui_Keyboard3, 105);
    lv_obj_set_width(ui_Keyboard3, 929);
    lv_obj_set_height(ui_Keyboard3, 177);
    //lv_obj_set_x(ui_Keyboard2, -24);
    //lv_obj_set_y(ui_Keyboard2, 105);
    lv_obj_set_x(ui_Keyboard3, -2);
    lv_obj_set_y(ui_Keyboard3, 110);
    lv_obj_set_align(ui_Keyboard3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard3,LV_OBJ_FLAG_HIDDEN);

    ui_Keyboard4 = lv_keyboard_create(ui_Screen11);

    lv_obj_set_width(ui_Keyboard4, 929);
    lv_obj_set_height(ui_Keyboard4, 177);

    lv_obj_set_x(ui_Keyboard4, -2);
    lv_obj_set_y(ui_Keyboard4, 110);
    lv_obj_set_align(ui_Keyboard4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard4,LV_OBJ_FLAG_HIDDEN);
 

/*
    lv_keyboard_set_textarea(ui_Keyboard2, ui_TextArea2);
    lv_keyboard_set_textarea(ui_Keyboard3, ui_TextArea3);

    lv_obj_add_event_cb(ui_TextArea2, ui_event_TextArea2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
    
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard3, ui_event_Keyboard3, LV_EVENT_ALL, NULL);
    */

    lv_obj_add_event_cb(ui_TextArea4, ui_event_TextArea4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard4, ui_event_Keyboard4, LV_EVENT_ALL, NULL);



    lv_obj_add_event_cb(Enter_Button, ui_event_Enter_Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Image45, ui_event_Back_Button, LV_EVENT_ALL, NULL);

    lv_keyboard_set_textarea(ui_Keyboard4, ui_TextArea4);


  //  lv_textarea_set_accepted_chars(ui_TextArea2, "0123456789");
  //  lv_textarea_set_accepted_chars(ui_TextArea3, "0123456789");
    lv_textarea_set_accepted_chars(ui_TextArea4, "0123456789");


  //  lv_textarea_set_text(ui_TextArea2,"");
  //  lv_textarea_set_text(ui_TextArea3,"");
    lv_textarea_set_text(ui_TextArea4,"");




}

void ui_Screen11_screen_destroy(void)
{
    if(ui_Screen11) lv_obj_del(ui_Screen11);

    // NULL screen variables
    ui_Screen11 = NULL;
    ui_Keyboard2 = NULL;
    ui_TextArea2 = NULL;
    ui_TextArea3 = NULL;

}

