// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;//

lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel7 = NULL;

lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;


extern lv_timer_t* mytimer;
// event funtions
void ui_event_Image33(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
         lv_timer_del(mytimer);
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_LEFT, 50, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 13);
    lv_obj_set_y(ui_Label7, -81);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Chúng tôi vô cùng cảm ơn phản hồi của quý khách!");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_BOLD_VN35, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Image18 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image18, &ui_img_608776254);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_Image18, 6);
    lv_obj_set_y(ui_Image18, 104);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel7, 1028);
    lv_obj_set_height(ui_Panel7, 130);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -237);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xA59898), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image19 = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Image19, &ui_img_27268529);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 72
    lv_obj_set_x(ui_Image19, -3);
    lv_obj_set_y(ui_Image19, 0);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

 //   lv_obj_add_event_cb(ui_Image17, ui_event_Image33, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Label7 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Panel7 = NULL;
    ui_Image19 = NULL;

}
